name: Deploy to GitHub Pages

on:
  push:
    branches: ['main']

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Compile Pages
        run: go run main.go

      - name: Create artifact
        run: tar -cvf pages.tar.gz gen 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: gen 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
